### ISSUE TITLE
Where should we eat? (Nov 5th)

### ISSUE THREAD

**Issue by MylesBorins** [dimsumjs/pdx#1]
I'm imagining we meet between noon and one... BUT WHERE

**Comment by imakewebthings** [comment]
I've only been to Dim sum places in the Jade district near my house. I can confirm that HK Cafe and Ocean
City are acceptable. I have no idea outside of this area. Anyone else have favorites?

**Comment by nebrius** [comment]
My flights not till 5 on the 5th, yay!

**Comment by MylesBorins** [comment]
yayaya!

**Comment by MilanLoveless** [comment]
All the good ones are out on East 82nd I hear. It'll be tough to get out there given that I work downtown. Is anyone driving or want to split a car2go with me?

**Comment by RuthieB** [comment]
Sorry it took me so long to get this info, but I hear from a trusted source that Wong's King is the place to go....  http://www.wongsking.com/

I'm not sure if I can make it or not, but I thought I'd share what I know. :)

**Comment by MylesBorins** [comment]
Hey All, I think the combination of how far dim sum seems to be from where people work, as well as some unexpected work conflicts, that we may have to delay this edition of dimsumjs

Please yell at me immediately if that is a problem

**Comment by MylesBorins** [comment]
Well, this didn't happen. SAWWWY
